fn called with input
err called with input
FN OUTPUT
[Error: fail]
